services:
  - type: web
    name: mindbridge
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn mindbridge.wsgi:application