# LEVEL 1 — General Screening (10 questions, sabke liye same)
LEVEL1_QUESTIONS = [
    {
        "id": "q1",
        "text": "How often do you feel sad or empty inside?",
        "options": [
            {"label": "Never",       "value": 0},
            {"label": "Rarely",      "value": 1},
            {"label": "Sometimes",   "value": 2},
            {"label": "Often",       "value": 3},
            {"label": "Always",      "value": 4},
        ]
    },
    {
        "id": "q2",
        "text": "How would you rate your energy levels throughout the day?",
        "options": [
            {"label": "Very high — always energetic",  "value": 0},
            {"label": "Good — mostly energetic",       "value": 1},
            {"label": "Average — sometimes tired",     "value": 2},
            {"label": "Low — often exhausted",         "value": 3},
            {"label": "Very low — no energy at all",   "value": 4},
        ]
    },
    {
        "id": "q3",
        "text": "How well are you sleeping lately?",
        "options": [
            {"label": "Excellent — 7-8 hrs, feel rested",   "value": 0},
            {"label": "Good — mostly fine",                 "value": 1},
            {"label": "Average — occasional issues",        "value": 2},
            {"label": "Poor — trouble sleeping often",      "value": 3},
            {"label": "Very poor — barely sleeping",        "value": 4},
        ]
    },
    {
        "id": "q4",
        "text": "How often do you enjoy activities you used to love?",
        "options": [
            {"label": "Always enjoy them",           "value": 0},
            {"label": "Most of the time",            "value": 1},
            {"label": "Sometimes",                   "value": 2},
            {"label": "Rarely enjoy anything",       "value": 3},
            {"label": "Nothing feels enjoyable",     "value": 4},
        ]
    },
    {
        "id": "q5",
        "text": "How connected do you feel to people around you?",
        "options": [
            {"label": "Very connected — great relationships", "value": 0},
            {"label": "Mostly connected",                     "value": 1},
            {"label": "Somewhat connected",                   "value": 2},
            {"label": "Mostly isolated",                      "value": 3},
            {"label": "Completely alone",                     "value": 4},
        ]
    },
    {
        "id": "q6",
        "text": "How often do you feel anxious or worried?",
        "options": [
            {"label": "Never",                      "value": 0},
            {"label": "Occasionally",               "value": 1},
            {"label": "Sometimes",                  "value": 2},
            {"label": "Frequently",                 "value": 3},
            {"label": "Almost constantly",          "value": 4},
        ]
    },
    {
        "id": "q7",
        "text": "How is your appetite and eating pattern?",
        "options": [
            {"label": "Very healthy — regular meals",    "value": 0},
            {"label": "Mostly good",                     "value": 1},
            {"label": "Sometimes skip meals",            "value": 2},
            {"label": "Often not eating properly",       "value": 3},
            {"label": "No appetite at all",              "value": 4},
        ]
    },
    {
        "id": "q8",
        "text": "How often do you feel hopeful about your future?",
        "options": [
            {"label": "Always hopeful",              "value": 0},
            {"label": "Mostly positive",             "value": 1},
            {"label": "Uncertain",                   "value": 2},
            {"label": "Mostly pessimistic",          "value": 3},
            {"label": "No hope at all",              "value": 4},
        ]
    },
    {
        "id": "q9",
        "text": "How well can you concentrate on tasks?",
        "options": [
            {"label": "Very well — fully focused",   "value": 0},
            {"label": "Mostly fine",                 "value": 1},
            {"label": "Sometimes distracted",        "value": 2},
            {"label": "Often struggle to focus",     "value": 3},
            {"label": "Cannot concentrate at all",   "value": 4},
        ]
    },
    {
        "id": "q10",
        "text": "Overall, how would you describe your mood right now?",
        "options": [
            {"label": "Excellent — very happy",      "value": 0},
            {"label": "Good — generally positive",   "value": 1},
            {"label": "Okay — neutral",              "value": 2},
            {"label": "Low — struggling",            "value": 3},
            {"label": "Very low — in pain",          "value": 4},
        ]
    },
]

# LEVEL 2 — Depression Path
LEVEL2_DEPRESSION = [
    {"id": "d1", "text": "How often do you feel worthless or like a burden to others?",
     "options": [{"label": "Never", "value": 0}, {"label": "Rarely", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Often", "value": 3},
                 {"label": "Always", "value": 4}]},
    {"id": "d2", "text": "Do you have thoughts of harming yourself or not wanting to be here?",
     "options": [{"label": "Never", "value": 0}, {"label": "Rarely", "value": 1},
                 {"label": "Occasionally", "value": 2}, {"label": "Often", "value": 3},
                 {"label": "Very often", "value": 4}]},
    {"id": "d3", "text": "How often do you cry without knowing why?",
     "options": [{"label": "Never", "value": 0}, {"label": "Rarely", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Frequently", "value": 3},
                 {"label": "Almost daily", "value": 4}]},
    {"id": "d4", "text": "Do you feel emotionally numb or disconnected from everything?",
     "options": [{"label": "Not at all", "value": 0}, {"label": "Slightly", "value": 1},
                 {"label": "Moderately", "value": 2}, {"label": "Significantly", "value": 3},
                 {"label": "Completely numb", "value": 4}]},
    {"id": "d5", "text": "How often do you avoid going out or meeting people?",
     "options": [{"label": "Never", "value": 0}, {"label": "Rarely", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Often", "value": 3},
                 {"label": "Always stay isolated", "value": 4}]},
    {"id": "d6", "text": "Has your interest in work, studies or daily responsibilities dropped?",
     "options": [{"label": "Not at all", "value": 0}, {"label": "Slightly", "value": 1},
                 {"label": "Noticeably", "value": 2}, {"label": "Significantly", "value": 3},
                 {"label": "Completely lost interest", "value": 4}]},
    {"id": "d7", "text": "How long have you been feeling this way?",
     "options": [{"label": "Just a few days", "value": 0}, {"label": "About a week", "value": 1},
                 {"label": "2-4 weeks", "value": 2}, {"label": "1-3 months", "value": 3},
                 {"label": "More than 3 months", "value": 4}]},
    {"id": "d8", "text": "Do you feel like things will never get better?",
     "options": [{"label": "No — I have hope", "value": 0}, {"label": "Sometimes I wonder", "value": 1},
                 {"label": "Often feel this way", "value": 2}, {"label": "Most of the time", "value": 3},
                 {"label": "Yes — no hope", "value": 4}]},
    {"id": "d9", "text": "Are you able to perform basic self-care (shower, eat, sleep)?",
     "options": [{"label": "Yes fully", "value": 0}, {"label": "Mostly yes", "value": 1},
                 {"label": "Struggling sometimes", "value": 2}, {"label": "Often neglecting", "value": 3},
                 {"label": "Cannot manage at all", "value": 4}]},
    {"id": "d10", "text": "Do you have someone you can talk to about how you feel?",
     "options": [{"label": "Yes — strong support system", "value": 0},
                 {"label": "A few people", "value": 1},
                 {"label": "One person maybe", "value": 2},
                 {"label": "No one really", "value": 3},
                 {"label": "Completely alone", "value": 4}]},
]

# LEVEL 2 — Normal Path
LEVEL2_NORMAL = [
    {"id": "n1", "text": "How well do you manage stress in your daily life?",
     "options": [{"label": "Very well", "value": 0}, {"label": "Mostly well", "value": 1},
                 {"label": "Average", "value": 2}, {"label": "Struggle often", "value": 3},
                 {"label": "Cannot manage at all", "value": 4}]},
    {"id": "n2", "text": "How satisfied are you with your work or study performance?",
     "options": [{"label": "Very satisfied", "value": 0}, {"label": "Mostly satisfied", "value": 1},
                 {"label": "Neutral", "value": 2}, {"label": "Dissatisfied", "value": 3},
                 {"label": "Very dissatisfied", "value": 4}]},
    {"id": "n3", "text": "How often do you feel overwhelmed by responsibilities?",
     "options": [{"label": "Never", "value": 0}, {"label": "Rarely", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Often", "value": 3},
                 {"label": "Always overwhelmed", "value": 4}]},
    {"id": "n4", "text": "How is your work-life balance?",
     "options": [{"label": "Excellent balance", "value": 0}, {"label": "Mostly balanced", "value": 1},
                 {"label": "Somewhat balanced", "value": 2}, {"label": "Poor balance", "value": 3},
                 {"label": "No balance at all", "value": 4}]},
    {"id": "n5", "text": "How often do you engage in hobbies or activities you enjoy?",
     "options": [{"label": "Daily", "value": 0}, {"label": "Few times a week", "value": 1},
                 {"label": "Weekly", "value": 2}, {"label": "Rarely", "value": 3},
                 {"label": "Never", "value": 4}]},
    {"id": "n6", "text": "Do you feel your life has meaning and purpose?",
     "options": [{"label": "Absolutely", "value": 0}, {"label": "Mostly yes", "value": 1},
                 {"label": "Sometimes uncertain", "value": 2}, {"label": "Rarely feel purpose", "value": 3},
                 {"label": "No purpose at all", "value": 4}]},
    {"id": "n7", "text": "How are your relationships with family and friends?",
     "options": [{"label": "Very strong", "value": 0}, {"label": "Good", "value": 1},
                 {"label": "Average", "value": 2}, {"label": "Strained", "value": 3},
                 {"label": "Very poor", "value": 4}]},
    {"id": "n8", "text": "How often do you feel content with your current situation?",
     "options": [{"label": "Very often", "value": 0}, {"label": "Often", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Rarely", "value": 3},
                 {"label": "Never", "value": 4}]},
    {"id": "n9", "text": "How do you feel about your future prospects?",
     "options": [{"label": "Very optimistic", "value": 0}, {"label": "Optimistic", "value": 1},
                 {"label": "Uncertain", "value": 2}, {"label": "Worried", "value": 3},
                 {"label": "Very pessimistic", "value": 4}]},
    {"id": "n10", "text": "How often do you practice self-care (exercise, rest, nutrition)?",
     "options": [{"label": "Daily — very consistent", "value": 0}, {"label": "Often", "value": 1},
                 {"label": "Sometimes", "value": 2}, {"label": "Rarely", "value": 3},
                 {"label": "Never", "value": 4}]},
]

# LEVEL 2 — Happy Path
LEVEL2_HAPPY = [
    {"id": "h1", "text": "How often do you feel genuine joy and happiness?",
     "options": [{"label": "Almost always", "value": 4}, {"label": "Very often", "value": 3},
                 {"label": "Often", "value": 2}, {"label": "Sometimes", "value": 1},
                 {"label": "Rarely", "value": 0}]},
    {"id": "h2", "text": "How strong is your sense of gratitude for what you have?",
     "options": [{"label": "Extremely strong", "value": 4}, {"label": "Very strong", "value": 3},
                 {"label": "Moderate", "value": 2}, {"label": "Weak", "value": 1},
                 {"label": "Not present", "value": 0}]},
    {"id": "h3", "text": "How fulfilling are your personal relationships?",
     "options": [{"label": "Extremely fulfilling", "value": 4}, {"label": "Very fulfilling", "value": 3},
                 {"label": "Mostly good", "value": 2}, {"label": "Somewhat", "value": 1},
                 {"label": "Not fulfilling", "value": 0}]},
    {"id": "h4", "text": "How often do you feel proud of your achievements?",
     "options": [{"label": "Very often", "value": 4}, {"label": "Often", "value": 3},
                 {"label": "Sometimes", "value": 2}, {"label": "Rarely", "value": 1},
                 {"label": "Never", "value": 0}]},
    {"id": "h5", "text": "How well do you handle challenges without losing positivity?",
     "options": [{"label": "Extremely well", "value": 4}, {"label": "Very well", "value": 3},
                 {"label": "Mostly well", "value": 2}, {"label": "Struggle sometimes", "value": 1},
                 {"label": "Find it very hard", "value": 0}]},
    {"id": "h6", "text": "How often do you help or support others?",
     "options": [{"label": "Very often — it brings me joy", "value": 4},
                 {"label": "Often", "value": 3}, {"label": "Sometimes", "value": 2},
                 {"label": "Rarely", "value": 1}, {"label": "Never", "value": 0}]},
    {"id": "h7", "text": "How aligned is your daily life with your personal values?",
     "options": [{"label": "Completely aligned", "value": 4}, {"label": "Mostly aligned", "value": 3},
                 {"label": "Somewhat", "value": 2}, {"label": "Rarely aligned", "value": 1},
                 {"label": "Not at all", "value": 0}]},
    {"id": "h8", "text": "How often do you experience moments of deep contentment?",
     "options": [{"label": "Daily", "value": 4}, {"label": "Often", "value": 3},
                 {"label": "Sometimes", "value": 2}, {"label": "Rarely", "value": 1},
                 {"label": "Almost never", "value": 0}]},
    {"id": "h9", "text": "How clear are you about your life goals and purpose?",
     "options": [{"label": "Crystal clear", "value": 4}, {"label": "Mostly clear", "value": 3},
                 {"label": "Somewhat clear", "value": 2}, {"label": "Confused", "value": 1},
                 {"label": "No idea", "value": 0}]},
    {"id": "h10", "text": "How often do you look forward to the next day?",
     "options": [{"label": "Almost always", "value": 4}, {"label": "Very often", "value": 3},
                 {"label": "Sometimes", "value": 2}, {"label": "Rarely", "value": 1},
                 {"label": "Never", "value": 0}]},
]